<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getChoicesGroupByCategory()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p, c');

        $qb->leftJoin('p.category', 'c');
        $qb->orderBy('c.name', 'ASC')->addOrderBy('p.name', 'ASC');

        $products = $qb->getQuery()->execute();

        $choices = array();
        foreach ($products as $product) {
            $choices[$product->getCategory()->getName()][] = $product;
        }

        return $choices;
    }
}
